name: 🚀 Feature Request
description: Suggest an idea to help us improve the package
title: "[🚀]: "
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: Thank you for taking the time to fill out this feature request report!
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for your feature.
    options:
    - label: I have searched the [issues](https://github.com/8bou3/EventEmitter.jl/issues) and found no similar feature requests
      required: true
- type: textarea
  attributes:
    label: Issues/Problems
    placeholder: A concise description of what you're trying to solve.
- type: textarea
  attributes:
    label: Suggested Solution
    placeholder: A concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives
    placeholder: A concise description of any alternative solutions or features you've considered.
- type: textarea
  attributes:
    label: Anything else?
    description: Links? References? Anything that will give us more context about the issue you are encountering!
    placeholder: You can attach images or log files by clicking this area to highlight it and then dragging files in.
